version: '3.3'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    logging:
      driver: none
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    logging:
      driver: none
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    healthcheck:
      test: "/usr/bin/kafka-topics --list --zookeeper zookeeper:2181"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - 9042:9042
    volumes:
      - "./cassandra-init.sh:/cassandra-init.sh"
    command: "sh /cassandra-init.sh"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5
#      - "9160:9160"
#      - "7199:7199"

  producer:
    build: producer
    container_name: producer
    entrypoint: /wait-for-it.sh cassandra:9042 -- java -jar app.jar
    depends_on:
      - kafka
      - cassandra
    ports:
      - 8080:8080

  consumer:
    build: consumer
    container_name: consumer
    entrypoint: /wait-for-it.sh cassandra:9042 -- java -jar app.jar
    depends_on:
      - kafka
      - cassandra
      - producer
    ports:
      - 8090:8090
