server:
  port: 8080
spring:
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    cassandra:
      port: 9042
      contact-points: cassandra
      keyspace-name: userspace
      schema-action: create_if_not_exists
      user-name: cassandra
      password: cassandra
      local-datacenter: datacenter1

